
spring:
  datasource:
    username: root
    password: yiqiandewo1
    url: jdbc:mysql://120.24.218.221:3306/blog?serverTimezone=UTC&useUnicode=true&characterEnconding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true # Spring Boot 的 META-INF/spring-configuration-metadata.json 配置文件中默认是关闭 Spring 的 hiddenmethod 过滤器的。
                      # 这时候需要通Springboot配置文件application.yml/properties 中将 hiddenmethod 过滤器设置为启用即可。 可以配置delete put等请求
  messages:
    basename: i18n.messages # 国际化的配置文件路径
  redis:
    host: 120.24.218.221
    port: 6379
    password: 123
mybatis:
  type-aliases-package: com.yiqiandewo.pojo
  mapper-locations: classpath:com/yiqiandewo/mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
logging:
  level:
    com.yiqiandewo.mapper: debug  # 控制台打印sql

comment.avatar: https://i.loli.net/2021/05/02/QAioDNPKlZVutY4.png
server:
  port: 80
  servlet:
    context-path: /blog # 项目名 ContextPath must start with '/' and not end with '/'